import nodemailer from 'nodemailer';
import { config } from '../config/index.js';

const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: config.email.user,
    pass: config.email.pass
  }
});

export const sendCertificateEmail = async (toEmail, name, pledgeId, pdfBuffer) => {
  try {
    const mailOptions = {
      from: `"Say No To Drugs Campaign" <${config.email.user}>`,
      to: toEmail,
      subject: 'Your Say No to Drugs Pledge Certificate',
      html: `
        <div style="font-family: Arial, sans-serif; color: #333;">
          <h2>Dear ${name},</h2>
          <p>Thank you for taking the Say No to Drugs Pledge.</p>
          <p>Your commitment helps spread awareness and encourages a healthier, safer and drug-free society.</p>
          <p><strong>Pledge ID:</strong> ${pledgeId}</p>
          <p>Your digital pledge certificate is attached.</p>
          <p>Thank you for being part of the campaign.</p>
          <br>
          <p>Say No to Drugs. Say Yes to Life.</p>
        </div>
      `,
      attachments: [
        {
          filename: `certificate-${pledgeId}.pdf`,
          content: pdfBuffer,
          contentType: 'application/pdf'
        }
      ]
    };

    const info = await transporter.sendMail(mailOptions);
    console.log('Email sent:', info.messageId);
    return true;
  } catch (error) {
    console.error('Error sending email:', error);
    return false;
  }
};

export const sendOtpEmail = async (toEmail, name, otp) => {
  try {
    const mailOptions = {
      from: `"Say No To Drugs Campaign" <${config.email.user}>`,
      to: toEmail,
      subject: 'Your Admin Login OTP',
      html: `
        <div style="font-family: Arial, sans-serif; color: #333; max-width: 500px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 8px; padding: 24px;">
          <h2 style="color: #FF9933; text-align: center;">Admin Verification</h2>
          <p>Dear ${name},</p>
          <p>To securely access the admin dashboard, please use the following One-Time Password (OTP):</p>
          <div style="background-color: #f5f5f5; border-radius: 8px; padding: 16px; text-align: center; margin: 20px 0;">
            <span style="font-size: 32px; font-weight: bold; letter-spacing: 4px; color: #1a1a1a;">${otp}</span>
          </div>
          <p>This OTP is valid for 10 minutes. Do not share this code with anyone.</p>
          <br>
          <p style="font-size: 12px; color: #888; text-align: center;">Securely generated by Veagle Space.</p>
        </div>
      `
    };

    const info = await transporter.sendMail(mailOptions);
    console.log('OTP Email sent:', info.messageId);
    return true;
  } catch (error) {
    console.error('Error sending OTP email:', error);
    return false;
  }
};
