name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22

          script: |
            cd /root/saynotodrugs

            git fetch origin main
            git reset --hard origin/main

            echo "Server updating"

            cd server
            npm install
            npx prisma generate
            npx prisma db push
            pm2 restart saynotodrugs-server

            echo "Frontend updating"

            cd ../client
            rm -rf .next
            npm install
            npm run build
            pm2 restart saynotodrugs-client

            echo "Deployment completed"
